jobs:
  build:
  steps:
    - store_artifacts:
          path: /htmlcov
machine:
  python:
    version: 3.5.0

test:
  override:
    - coverage run -m unittest discover -p *_test.py
    - coverage report --fail-under=80
    - coverage html --include=tests/\*
  post:
    - mv htmlcov  $CIRCLE_ARTIFACTS/coverage-report
